### ISSUE TITLE
安装后无法启动，请问该如何解决？

### ISSUE THREAD

**Issue by nanbowanya** [rootlexblog/hexo-ai-excerpt#1]
配置文件中用的gpt的API地址，且已填写可以使用的apikey。
<img width="445" alt="image" src="https://github.com/rootlexme/hexo-ai-excerpt/assets/20452341/3d726ffe-dce1-4992-8fa1-a3ac7aecf471">
执行过程中会提示摘要完成，但是就是无法启动服务。
<img width="978" alt="image" src="https://github.com/rootlexme/hexo-ai-excerpt/assets/20452341/2a9c1ddc-b55d-4fd3-957b-7b009e2e5643">

另外如果想设置页面不启用摘要，或者只在某些页面启用摘要该如何设置？

**Comment by rootlexme** [comment]
麻烦您检查一下node版本

**Comment by nanbowanya** [comment]
<img width="562" alt="image" src="https://github.com/rootlexme/hexo-ai-excerpt/assets/20452341/f5fb9667-6078-47e2-9cdb-d925e460ad0f">

**Comment by Shiguang-coding** [comment]
我也遇到类似问题，提示生成成功，访问文章没有任何变化，也不知道正常应该是什么样子
